import { StyleSheet } from "@react-pdf/renderer";

export const styles = StyleSheet.create({
  page: { padding: 30, fontSize: 9, color: "#0f172a", fontFamily: "Helvetica", lineHeight: 1.4 },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    borderBottom: "1px solid #e2e8f0",
    paddingBottom: 8,
  },
  brand: { fontSize: 15, fontFamily: "Helvetica-Bold", color: "#16a34a" },
  brandSub: { fontSize: 8, color: "#64748b" },
  title: { fontSize: 11, fontFamily: "Helvetica-Bold", textAlign: "right", maxWidth: 200 },
  section: { marginTop: 12 },
  sectionTitle: {
    fontSize: 10,
    fontFamily: "Helvetica-Bold",
    marginBottom: 5,
    color: "#334155",
    textTransform: "uppercase",
  },
  grid2: { flexDirection: "row", flexWrap: "wrap" },
  cell: { width: "50%", flexDirection: "row", justifyContent: "space-between", paddingVertical: 1.5, paddingRight: 10 },
  row: { flexDirection: "row", justifyContent: "space-between", paddingVertical: 1.5 },
  label: { color: "#64748b" },
  value: { fontFamily: "Helvetica-Bold" },
  checklistWrap: { flexDirection: "row", flexWrap: "wrap" },
  li: { width: "50%", flexDirection: "row", justifyContent: "space-between", paddingVertical: 1, paddingRight: 10 },
  ok: { color: "#16a34a", fontFamily: "Helvetica-Bold" },
  fail: { color: "#dc2626", fontFamily: "Helvetica-Bold" },
  damagesWrap: { flexDirection: "row", gap: 12, alignItems: "flex-start" },
  croquisBox: { width: 90 },
  damagesList: { flex: 1 },
  photos: { flexDirection: "row", flexWrap: "wrap", gap: 6, marginTop: 4 },
  photo: { width: 110, height: 82, objectFit: "cover", borderRadius: 3 },
  signatureBox: { marginTop: 10, borderTop: "1px solid #e2e8f0", paddingTop: 8 },
  signatureImg: { width: 180, height: 70, objectFit: "contain" },
  small: { fontSize: 8, color: "#64748b", marginTop: 3 },
  legalP: { fontSize: 8, color: "#334155", marginBottom: 6, textAlign: "justify" },
  footer: { position: "absolute", bottom: 20, left: 30, right: 30, fontSize: 7, color: "#94a3b8", textAlign: "center" },
});
